### PR TITLE
feat: Add iframe zoom animation

### PR DESCRIPTION
**Pull request by ErikQQY**
This pull request add GSAP animation library to support more animation.

Because the original casdoor iframe being narrowed, it looks blurring. Now when we put cursor on the header iframe, we can zoom in the iframe to make it more distinct.

Signed-off-by: ErikQQY <2283984853@qq.com>

### CODE REVIEW

**Comment by ErikQQY** [comment]
@hsluoyz Plz review.
If the animation looks well, I will add more for the whole page.

**Comment by hsluoyz** [comment]
@ErikQQY it looks good in PC! Does it work for mobile?

**Comment by ErikQQY** [comment]
I modified the layout, the mobile looking is working well.

**Comment by hsluoyz** [comment]
It's a little weird. Actually zoom animation is not a must here. Maybe we should not put more efforts in this area. We should improve the docs content first.

image

**Pull request closed without merging**
