### PR TITLE
docs: add docs for springcloud integration

### PR DESCRIPTION
**Pull request by leo220yuyaodog**

### CODE REVIEW

**Comment by hsluoyz** [comment]
@seriouszyx plz review

**Comment by seriouszyx** [comment]
@leo220yuyaodog why I can't see the spring-cloud in the sidebar

image

**Comment by leo220yuyaodog** [comment]
> @leo220yuyaodog why I can't see the spring-cloud in the sidebar
> 
> image
> 
> Maybe you need to update sidebar.js

 I did not update sidebar.js

**Comment by leo220yuyaodog** [comment]
> @leo220yuyaodog why I can't see the spring-cloud in the sidebar
> 
> image
> 
> Maybe you need to update sidebar.js

I updated sidebar.js . Does it show up now?

**Comment by seriouszyx** [comment]
> > @leo220yuyaodog why I can't see the spring-cloud in the sidebar
> 
> > 
> 
> > image
> 
> > 
> 
> > Maybe you need to update sidebar.js
> 
> 
> 
> I updated sidebar.js . Does it show up now?

Yes, pay attention to the format, some codes can't be parsed 

image

**Comment by leo220yuyaodog** [comment]
@seriouszyx I fixed the worry format . sorry to bother you so many times

**Pull request merged**
