### PR TITLE
fix: mobile view

### PR DESCRIPTION
**Pull request by mdathar4403**

### CODE REVIEW

**Comment by leo220yuyaodog** [comment]
@mdathar4403 plz sign CLA 
image

**Comment by mdathar4403** [comment]
> @mdathar4403 plz sign CLA image

Done✅

**Comment by hsluoyz** [comment]
@mdathar4403 this is not really a fix, as it only hard-coded to another value

**Comment by mdathar4403** [comment]
> @mdathar4403 this is not really a fix, as it only hard-coded to another value

Yeah!! so to avoid that overflow only that little thing was needed

**Pull request closed without merging**
