### PR TITLE
overflow-fixed

### PR DESCRIPTION
**Pull request by mdathar4403**
Component that was overflowing in mobile view has been fixed !!!

### CODE REVIEW

**Comment by hsluoyz** [comment]
@mdathar4403 fix:

image

**Comment by mdathar4403** [comment]
> @mdathar4403 fix:
> 
> image

Can you plz tell me how to fix this ??

**Comment by leo220yuyaodog** [comment]
> > @mdathar4403 fix:
> > image
> 
> Can you plz tell me how to fix this ??
See our [contributing guidelines](https://github.com/casdoor/casdoor-website/blob/eca1426c300d1cbe63d8da2d1ca1e4e0b5cc317e/docs/contributing.md).

**Comment by leo220yuyaodog** [comment]
@mdathar4403 Hi, also need to modify the title as `fix: mobile view`
image

**Pull request closed without merging**
