### PR TITLE
fix: Adjust the homepage description and login box to align with the edge

### PR DESCRIPTION
**Pull request by yanchaomei**

### CODE REVIEW

**Comment by Selflocking** [comment]
Please sign the CLA:
image

And Please submit a semantic commit and PR: https://casdoor.org/docs/contributing#semantic-prs
like: `fix: xxxxxx`.

**Comment by leo220yuyaodog** [comment]
@yanchaomei Hi, you can refer to [contributor guide](the https://casdoor.org/docs/contributing#semantic-prs). It will help you pass the semantic PR errer.

**Comment by Selflocking** [comment]
You can run this to change the commit message:
```bash
git commit --amend
git push -f
```
https://git-scm.com/book/en/v2/Git-Basics-Undoing-Things

**Comment by yanchaomei** [comment]
> 

get it, thank you!

**Review by leo220yuyaodog — APPROVED** [review]

**Review by Selflocking — APPROVED** [review]

**Pull request merged**
