### PR TITLE
docs: add bypassing Password Encryption during user import

### PR DESCRIPTION
**Pull request by yescine**
https://github.com/casdoor/casdoor/issues/2282

### CODE REVIEW

**Comment by hsluoyz** [comment]
@yescine plz fix:

image

**Comment by yescine** [comment]
@hsluoyz the lint command didn' t worked on my windows machine, I run it manually.

**Comment by Selflocking** [comment]
image
image

Your commits must also satisfy the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)

**Comment by Selflocking** [comment]
> @hsluoyz the lint command didn' t worked on my windows machine, I run it manually.

If this is your first time using it, you must first install the dependencies before executing the lint command: 

```bash
yarn
yarn lint:md
```

**Pull request merged**
