### PR TITLE
docs: add sdk intro page

### PR DESCRIPTION
**Pull request by sh1luo**
Fix: #29 
Signed-off-by: sh1luo <690898835@qq.com>

### CODE REVIEW

**Comment by hsluoyz** [comment]
@sh1luo add screenshot pictures, give default values or example values for each field.

**Comment by sh1luo** [comment]
> @sh1luo add screenshot pictures, give default values or example values for each field.

@hsluoyz ok, but where to store the screenshot picture file, [static](https://github.com/casbin/static)?

**Review by ErikQQY — APPROVED** [review]
I think add the example of Casnode and Casbin-OA using the Casdoor SDK is better

**Comment by hsluoyz** [comment]
@sh1luo just inside this repo, see the user images: https://casbin.org/en/users

**Comment by sh1luo** [comment]
> @sh1luo just inside this repo, see the user images: https://casbin.org/en/users

ok, working on it.

**Comment by hsluoyz** [comment]
@sh1luo any update?

**Comment by sh1luo** [comment]
> @sh1luo any update?

@hsluoyz Done.

**Pull request merged**
