### PR TITLE
docs: add firezone oidc configuration document

### PR DESCRIPTION
**Pull request by dingchenzy**

### CODE REVIEW

**Comment by hsluoyz** [comment]
@dingchenzy sign CLA

image

**Comment by hsluoyz** [comment]
@leo220yuyaodog @Selflocking @yoyo314 plz review

**Comment by dingchenzy** [comment]
> @dingchenzy sign CLA
> 
> image

I'm already logged in

**Comment by hsluoyz** [comment]
Replaced by: https://github.com/casdoor/casdoor-website/pull/398

**Pull request closed without merging**
