### PR TITLE
docs: add ldap docs

### PR DESCRIPTION
**Pull request by WindSpiritSR**
Continue: https://github.com/casbin/casdoor/pull/160

Signed-off-by: WindSpiritSR <simon343riley@gmail.com>

### CODE REVIEW

**Comment by hsluoyz** [comment]
@WindSpiritSR plz fix:

image

**Comment by hsluoyz** [comment]
@ErikQQY @Kininaru plz review

**Review by ErikQQY — CHANGES_REQUESTED** [review]
I think you didn't modify **sidebar.js** to add  the newly added docs, it causes the ldap docs can't display properly, please fix it.

**Comment by WindSpiritSR** [comment]
@ErikQQY thanks, fixed

**Review by ErikQQY — APPROVED** [review]

**Pull request merged**
