### PR TITLE
docs: add Nginx Community Version

### PR DESCRIPTION
**Pull request by GZYZhy**
Previously offered documents only provides tutorials for using Casdoor and Nginx Plus together. Based on my own usage experience, I have written a guide for using Casdoor with the Nginx community open source version. In this article, the human readable language I use is Chinese (Simplified). If there is anything wrong or inappropriate, please do not hesitate to advise.

### CODE REVIEW

**Comment by hsluoyz** [comment]
@GZYZhy hi, contribution like this PR is welcomed! One thing needs to be noted is that all docs in this repo should be in English, including all texts and the UI in screenshots. The translations into other languages like zh will be handled by another process named Crowdin (which is not included in this PR). So can you please change the PR into English only? ChatGPT will be a good help for this work.

**Comment by GZYZhy** [comment]
Okay, I have changed the language used in the article to English (using ChatGPT as an auxiliary tool), and the prompts in the pictures used in the article have been used in English, too. Thank you for your inspection. Wish you a happy New Year.

**Comment by hsluoyz** [comment]
@GZYZhy plz fix CI errors:

image

**Comment by GZYZhy** [comment]
I have reviewed the error message, and it indicates that the error occurred in the following file: `docs/provider/oauth/overview.md`. 

image

Strangely, this file is completely unrelated to my current pull request. According to my memory and the Git commit history, I haven't made any modifications to that file.

I have thoroughly reviewed all 7 files related to my pull request and checked them one by one using yarn and VSCode to ensure there are no errors.

To verify if my changes caused the error in that file, I cloned your official repository (i.e., casdoor/casdoor-website.git) again on my computer, which contains all the content before I submitted the pull request. Then, I opened the file using VSCode with the lint plugin installed, and I found that it also showed Markdown syntax errors.

image

Based on this, I believe that the error did not originate from my end. I'm not very familiar with the content described in the `docs/provider/oauth/overview.md` file, and I'm unsure about what modifications should be made to make it syntactically correct without altering the original content. Therefore, I may not be able to fix this error.

Thank you for your review, and wish you a happy new year. If there's anything else you need, please let me know.

**Pull request merged**
