### PR TITLE
feat: memorize the language user last selected

### PR DESCRIPTION
**Pull request by Selflocking**
Preview: https://casdoor.yunshu.site/

### CODE REVIEW

**Comment by leo220yuyaodog** [comment]
https://user-images.githubusercontent.com/71440988/195295682-e7862ee1-30a7-48b9-8648-d15ae220b42f.mp4

The demo site not work well.

**Comment by Selflocking** [comment]
Please review again, @leo220yuyaodog https://casdoor.yunshu.site/

**Comment by hsluoyz** [comment]
@leo220yuyaodog

**Comment by Selflocking** [comment]
Preview: https://casdoor.yunshu.site/

**Review by leo220yuyaodog — APPROVED** [review]

**Pull request closed without merging**
